apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: http-nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-multitool
      protocol: TCP
      port: 8080
      targetPort: 8080
